import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import AudioCard from '@/components/AudioCard';
import EmptyState from '@/components/EmptyState';
import type { AudioLecture, Language } from '@/lib/types';
import { LANGUAGES, LANGUAGE_LABELS } from '@/lib/types';
import Icon from '@/components/Icon';

export const revalidate = 60;
const PAGE_SIZE = 24;
export default async function AudioPage({ searchParams }: { searchParams: { language?: string; q?: string; page?: string } }) {
  const supabase = createClient(); const language = searchParams.language as Language | undefined; const q = (searchParams.q ?? '').trim(); const page = Math.max(1, Number(searchParams.page) || 1); let query = supabase.from('audio_lectures').select('*, scholars(*), categories(*)', { count: 'exact' }).order('created_at', { ascending: false }); if (language) query = query.eq('language', language); if (q) { const safe = q.replace(/[,()]/g, ' '); query = query.or(`title.ilike.%${safe}%,description.ilike.%${safe}%`); } const { data, count } = await query.range((page - 1) * PAGE_SIZE, page * PAGE_SIZE - 1); const lectures = (data ?? []) as AudioLecture[]; const total = count ?? 0; const makeHref = (p: number, lang = language) => { const params = new URLSearchParams(); if (lang) params.set('language', lang); if (q) params.set('q', q); if (p > 1) params.set('page', String(p)); const value = params.toString(); return value ? `/audio?${value}` : '/audio'; };
  return <div className="page-enter space-y-8"><header className="flex flex-col gap-5 border-b border-line pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Listen at your pace</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight text-navy">Audio lectures</h1><p className="mt-2 text-sm text-ink/55">{total} lectures available to stream.</p></div><form className="flex w-full max-w-md gap-2"><input name="q" defaultValue={q} type="search" placeholder="Search lectures…" className="input"/><button className="btn-primary shrink-0">Search</button></form></header><div className="flex flex-wrap gap-2"><Link href={makeHref(1, undefined)} className={`rounded-md border px-3 py-1.5 text-xs font-bold ${!language ? 'border-blue-600 bg-blue-600 text-white' : 'border-line bg-white text-ink/65'}`}>All languages</Link>{LANGUAGES.map((lang) => <Link key={lang} href={makeHref(1, language === lang ? undefined : lang)} className={`rounded-md border px-3 py-1.5 text-xs font-bold ${language === lang ? 'border-blue-600 bg-blue-600 text-white' : 'border-line bg-white text-ink/65'}`}>{LANGUAGE_LABELS[lang]}</Link>)}</div>{lectures.length === 0 ? <EmptyState title="No lectures found." hint="Try a different language or search term." /> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{lectures.map((a) => <AudioCard key={a.id} lecture={a} />)}</div>}<nav className="flex items-center justify-between border-t border-line pt-5"><span className="text-xs text-ink/45">Showing {total === 0 ? 0 : (page - 1) * PAGE_SIZE + 1}–{Math.min(page * PAGE_SIZE, total)} of {total}</span><div className="flex gap-2">{page > 1 && <Link href={makeHref(page - 1)} className="btn-secondary px-3"><Icon name="arrowLeft" size={14} /> Previous</Link>}{page * PAGE_SIZE < total && <Link href={makeHref(page + 1)} className="btn-secondary px-3">Next <Icon name="arrowRight" size={14} /></Link>}</div></nav></div>;
}
