'use client';

import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { getProgress, setProgress, clearProgress } from '@/lib/progress';
import { getProgressCloud, setProgressCloud } from '@/lib/cloudProgress';
import { useCurrentUser } from '@/lib/useCurrentUser';
import { createClient } from '@/lib/supabase/client';
import { getOfflineBlob } from '@/lib/offlineStore';
import Icon from '@/components/Icon';

export type AudioTrack = { src: string; title: string; id?: string };
type AudioContextValue = { track: AudioTrack | null; playing: boolean; current: number; duration: number; speed: number; volume: number; muted: boolean; queue: AudioTrack[]; sleepMinutes: number | null; playTrack: (track: AudioTrack, queue?: AudioTrack[]) => void; toggle: () => void; seek: (value: number) => void; skip: (seconds: number) => void; setSpeed: (value: number) => void; setVolume: (value: number) => void; toggleMute: () => void; setSleep: (minutes: number | null) => void; next: () => void; previous: () => void; };
const AudioContext = createContext<AudioContextValue | null>(null);
function formatTime(seconds: number) { if (!Number.isFinite(seconds)) return '0:00'; return `${Math.floor(seconds / 60)}:${Math.floor(seconds % 60).toString().padStart(2, '0')}`; }

export function AudioProvider({ children }: { children: ReactNode }) {
  const { user } = useCurrentUser(); const audioRef = useRef<HTMLAudioElement>(null); const [track, setTrack] = useState<AudioTrack | null>(null); const [effectiveSrc, setEffectiveSrc] = useState(''); const [queue, setQueue] = useState<AudioTrack[]>([]); const [playing, setPlaying] = useState(false); const [current, setCurrent] = useState(0); const [duration, setDuration] = useState(0); const [speed, setSpeedState] = useState(1); const [volume, setVolumeState] = useState(1); const [muted, setMuted] = useState(false); const [sleepMinutes, setSleepMinutes] = useState<number | null>(null); const sleepTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const playTrack = useCallback((nextTrack: AudioTrack, nextQueue: AudioTrack[] = []) => { setTrack(nextTrack); setQueue(nextQueue); setCurrent(0); setPlaying(true); }, []);
  useEffect(() => { let cancelled = false; let blobUrl: string | null = null; if (!track) return; setEffectiveSrc(track.src); (async () => { if (track.id) { const blob = await getOfflineBlob('audio', track.id); if (!cancelled && blob) { blobUrl = URL.createObjectURL(blob); setEffectiveSrc(blobUrl); } } })(); return () => { cancelled = true; if (blobUrl) URL.revokeObjectURL(blobUrl); }; }, [track]);
  useEffect(() => { const el = audioRef.current; if (!el || !track) return; const onTime = () => { setCurrent(el.currentTime); if (track.id && Math.floor(el.currentTime) % 5 === 0) { setProgress('audio', track.id, el.currentTime); if (user) setProgressCloud(createClient(), user.id, 'audio', track.id, el.currentTime); } }; const onLoaded = () => { setDuration(el.duration); const saved = track.id ? (user ? undefined : getProgress('audio', track.id)) : undefined; if (saved && saved < el.duration - 2) el.currentTime = saved; }; const onEnded = () => { if (track.id) clearProgress('audio', track.id); const index = queue.findIndex((item) => item.id === track.id); if (index >= 0 && queue[index + 1]) playTrack(queue[index + 1], queue); else { setPlaying(false); setCurrent(0); } }; const onError = () => setPlaying(false); el.addEventListener('timeupdate', onTime); el.addEventListener('loadedmetadata', onLoaded); el.addEventListener('ended', onEnded); el.addEventListener('error', onError); return () => { el.removeEventListener('timeupdate', onTime); el.removeEventListener('loadedmetadata', onLoaded); el.removeEventListener('ended', onEnded); el.removeEventListener('error', onError); }; }, [playTrack, queue, track, user]);
  useEffect(() => { const el = audioRef.current; if (!el) return; el.playbackRate = speed; el.volume = volume; el.muted = muted; if (playing) void el.play().catch(() => setPlaying(false)); else el.pause(); }, [effectiveSrc, muted, playing, speed, volume]);
  useEffect(() => { if (sleepTimer.current) clearTimeout(sleepTimer.current); if (sleepMinutes && sleepMinutes > 0) sleepTimer.current = setTimeout(() => { audioRef.current?.pause(); setPlaying(false); setSleepMinutes(null); }, sleepMinutes * 60 * 1000); return () => { if (sleepTimer.current) clearTimeout(sleepTimer.current); }; }, [sleepMinutes]);
  useEffect(() => { if (!('mediaSession' in navigator) || !track) return; navigator.mediaSession.metadata = new MediaMetadata({ title: track.title, artist: 'Maktaba' }); navigator.mediaSession.setActionHandler('play', () => setPlaying(true)); navigator.mediaSession.setActionHandler('pause', () => setPlaying(false)); navigator.mediaSession.setActionHandler('seekbackward', () => audioRef.current && (audioRef.current.currentTime -= 15)); navigator.mediaSession.setActionHandler('seekforward', () => audioRef.current && (audioRef.current.currentTime += 15)); }, [track]);
  const toggle = () => setPlaying((value) => !value); const seek = (value: number) => { if (audioRef.current) audioRef.current.currentTime = value; setCurrent(value); }; const skip = (seconds: number) => seek(Math.min(Math.max((audioRef.current?.currentTime ?? 0) + seconds, 0), duration || 0)); const setSpeed = (value: number) => setSpeedState(value); const setVolume = (value: number) => setVolumeState(value); const next = () => { const index = queue.findIndex((item) => item.id === track?.id); if (index >= 0 && queue[index + 1]) playTrack(queue[index + 1], queue); }; const previous = () => { const index = queue.findIndex((item) => item.id === track?.id); if (index > 0) playTrack(queue[index - 1], queue); };
  const value = useMemo(() => ({ track, playing, current, duration, speed, volume, muted, queue, sleepMinutes, playTrack, toggle, seek, skip, setSpeed, setVolume, toggleMute: () => setMuted((value) => !value), setSleep: setSleepMinutes, next, previous }), [current, duration, muted, next, playTrack, playing, previous, queue, seek, sleepMinutes, skip, speed, track, volume]);
  return <AudioContext.Provider value={value}><audio ref={audioRef} src={effectiveSrc} preload="metadata" />{children}{track && <div className="fixed inset-x-0 bottom-[68px] z-40 border-t border-line bg-navy text-white shadow-[0_-8px_24px_rgba(11,31,58,.18)] lg:bottom-0"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-2 sm:px-6 lg:px-8"><button type="button" onClick={previous} disabled={!queue.length} className="hidden text-blue-200 hover:text-white sm:block" aria-label="Previous track"><Icon name="prev" /></button><button type="button" onClick={toggle} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-blue-500 font-bold" aria-label={playing ? 'Pause' : 'Play'}><Icon name={playing ? 'pause' : 'play'} /></button><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{track.title}</p><input aria-label="Audio progress" type="range" min="0" max={duration || 0} step="0.1" value={current} onChange={(e) => seek(Number(e.target.value))} className="h-1 w-full accent-blue-300"/></div><span className="hidden text-[11px] text-blue-200 sm:block">{formatTime(current)} / {formatTime(duration)}</span><select aria-label="Sleep timer" value={sleepMinutes ?? ''} onChange={(e) => setSleepMinutes(e.target.value ? Number(e.target.value) : null)} className="hidden rounded-md border border-white/20 bg-transparent px-1 py-1 text-xs text-white sm:block"><option value="">Sleep</option><option value="15">15m</option><option value="30">30m</option><option value="45">45m</option><option value="60">60m</option></select><button type="button" onClick={next} disabled={!queue.length} className="hidden text-blue-200 hover:text-white sm:block" aria-label="Next track"><Icon name="next" /></button><button type="button" onClick={() => setTrack(null)} className="text-blue-200 hover:text-white" aria-label="Close player"><Icon name="close" /></button></div></div>}</AudioContext.Provider>;
}
export function useAudioPlayer() { const value = useContext(AudioContext); if (!value) throw new Error('useAudioPlayer must be used inside AudioProvider'); return value; }
