export type Language = 'pashto' | 'urdu' | 'english' | 'arabic';

export type PermissionStatus = 'authorized' | 'public_domain' | 'author_permission' | 'publisher_permission' | 'unknown';
export const PERMISSION_STATUS_LABELS: Record<PermissionStatus, string> = { authorized: 'Authorized for publication', public_domain: 'Public domain', author_permission: 'Published with author permission', publisher_permission: 'Published with publisher permission', unknown: 'Permission status not yet confirmed' };
export const LANGUAGES: Language[] = ['pashto', 'urdu', 'english', 'arabic'];
export type Category = { id: string; name: string; language: Language; created_at: string };
export type Scholar = { id: string; name: string; bio: string | null; photo_url: string | null; created_at: string; arabic_name?: string | null; aliases?: string[]; languages?: Language[]; featured?: boolean };
export type Book = { id: string; title: string; author: string | null; description: string | null; language: Language; category_id: string | null; cover_url: string | null; pdf_url: string; created_at: string; categories?: Category | null; scholar_id?: string | null; scholars?: Scholar | null; seo_title?: string | null; seo_description?: string | null; search_keywords?: string | null; view_count?: number; permission_status?: PermissionStatus; permission_note?: string | null; copyright_note?: string | null; source_note?: string | null; featured?: boolean; storage_provider?: string; storage_bucket?: string | null; storage_path?: string | null; file_size?: number | null; mime_type?: string | null };
export type AudioLecture = { id: string; title: string; scholar_id: string | null; description: string | null; language: Language; category_id: string | null; audio_url: string; created_at: string; scholars?: Scholar | null; categories?: Category | null; view_count?: number; permission_status?: PermissionStatus; permission_note?: string | null; copyright_note?: string | null; source_note?: string | null; downloadable?: boolean; series_name?: string | null; part_number?: number | null; featured?: boolean; storage_provider?: string; storage_bucket?: string | null; storage_path?: string | null; file_size?: number | null; mime_type?: string | null };
export const LANGUAGE_LABELS: Record<Language, string> = { pashto: 'پښتو', urdu: 'اردو', english: 'English', arabic: 'العربية' };
export type Comment = { id: string; user_id: string; item_type: 'book' | 'audio'; item_id: string; parent_id: string | null; content: string; status: 'visible' | 'reported' | 'hidden' | 'deleted'; created_at: string; updated_at: string };
export type ReportReason = 'broken_pdf' | 'broken_audio' | 'incorrect_information' | 'wrong_cover' | 'missing_pages' | 'incorrect_scholar' | 'incorrect_category' | 'other';
export const REPORT_REASON_LABELS: Record<ReportReason, string> = { broken_pdf: 'Broken PDF', broken_audio: 'Broken audio', incorrect_information: 'Incorrect information', wrong_cover: 'Wrong cover image', missing_pages: 'Missing pages', incorrect_scholar: 'Incorrect scholar', incorrect_category: 'Incorrect category', other: 'Other problem' };
export type Report = { id: string; item_type: 'book' | 'audio'; item_id: string; reason: ReportReason; message: string | null; status: 'open' | 'resolved'; created_at: string };
export type Announcement = { id: string; message: string; link: string | null; active: boolean; created_at: string };
