import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import BookCard from '@/components/BookCard';
import EmptyState from '@/components/EmptyState';
import type { Book, Category, Language } from '@/lib/types';
import { LANGUAGES, LANGUAGE_LABELS } from '@/lib/types';
import Icon from '@/components/Icon';

export const revalidate = 60;
type Sort = 'recent' | 'title' | 'popular';
const PAGE_SIZE = 24;
export default async function BooksPage({ searchParams }: { searchParams: { language?: string; category?: string; sort?: string; q?: string; page?: string } }) {
  const supabase = createClient(); const language = searchParams.language as Language | undefined; const category = searchParams.category; const q = (searchParams.q ?? '').trim(); const page = Math.max(1, Number(searchParams.page) || 1); const sort: Sort = searchParams.sort === 'title' ? 'title' : searchParams.sort === 'popular' ? 'popular' : 'recent';
  const [{ data: categoryData }, result] = await Promise.all([supabase.from('categories').select('*').order('name'), (() => { let query = supabase.from('books').select('*, categories(*)', { count: 'exact' }); if (language) query = query.eq('language', language); if (category) query = query.eq('category_id', category); if (q) query = query.or(`title.ilike.%${q.replace(/[,()]/g, ' ')}%,author.ilike.%${q.replace(/[,()]/g, ' ')}%,description.ilike.%${q.replace(/[,()]/g, ' ')}%`); query = sort === 'title' ? query.order('title') : sort === 'popular' ? query.order('view_count', { ascending: false }) : query.order('created_at', { ascending: false }); return query.range((page - 1) * PAGE_SIZE, page * PAGE_SIZE - 1); })()]);
  const categories = (categoryData ?? []) as Category[]; const books = (result.data ?? []) as Book[]; const total = result.count ?? 0; const hasNext = page * PAGE_SIZE < total;
  const buildHref = (overrides: Record<string, string | null | undefined>) => { const params = new URLSearchParams(); const values = { language, category, sort: sort === 'recent' ? null : sort, q: q || null, page: String(page), ...overrides }; Object.entries(values).forEach(([k, v]) => { if (v && !(k === 'page' && v === '1')) params.set(k, v); }); const qs = params.toString(); return qs ? `/books?${qs}` : '/books'; };
  const pill = (active: boolean) => `whitespace-nowrap rounded-md border px-3 py-1.5 text-xs font-bold ${active ? 'border-blue-600 bg-blue-600 text-white' : 'border-line bg-white text-ink/65 hover:border-blue-400'}`;
  return <div className="page-enter space-y-8"><header className="flex flex-col gap-5 border-b border-line pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">The collection</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight text-navy">Books</h1><p className="mt-2 text-sm text-ink/55">{total} titles available to read.</p></div><form className="flex w-full max-w-md gap-2"><input name="q" defaultValue={q} type="search" placeholder="Search titles and authors…" className="input"/><button className="btn-primary shrink-0">Search</button></form></header><div className="flex flex-wrap gap-2"><Link href={buildHref({ language: null, page: '1' })} className={pill(!language)}>All languages</Link>{LANGUAGES.map((lang) => <Link key={lang} href={buildHref({ language: language === lang ? null : lang, page: '1' })} className={pill(language === lang)}>{LANGUAGE_LABELS[lang]}</Link>)}</div>{categories.length > 0 && <div className="flex gap-2 overflow-x-auto pb-1"><Link href={buildHref({ category: null, page: '1' })} className={pill(!category)}>All subjects</Link>{categories.map((c) => <Link key={c.id} href={buildHref({ category: category === c.id ? null : c.id, page: '1' })} className={pill(category === c.id)} dir="auto">{c.name}</Link>)}</div>}<div className="flex flex-wrap items-center gap-3 text-sm"><span className="font-semibold text-ink/45">Sort by</span>{(['recent', 'title', 'popular'] as Sort[]).map((value) => <Link key={value} href={buildHref({ sort: value === 'recent' ? null : value, page: '1' })} className={sort === value ? 'font-bold text-blue-700' : 'font-medium text-ink/60 hover:text-blue-700'}>{value === 'recent' ? 'Recently added' : value === 'title' ? 'Title A–Z' : 'Most read'}</Link>)}</div>{books.length === 0 ? <EmptyState title="No books found." hint="Try a different filter or search term." /> : <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-5 lg:grid-cols-6">{books.map((b) => <BookCard key={b.id} book={b} />)}</div>}<nav className="flex items-center justify-between border-t border-line pt-5" aria-label="Books pagination"><span className="text-xs text-ink/45">Showing {total === 0 ? 0 : (page - 1) * PAGE_SIZE + 1}–{Math.min(page * PAGE_SIZE, total)} of {total}</span><div className="flex gap-2">{page > 1 && <Link href={buildHref({ page: String(page - 1) })} className="btn-secondary px-3"><Icon name="arrowLeft" size={14} /> Previous</Link>}{hasNext && <Link href={buildHref({ page: String(page + 1) })} className="btn-secondary px-3">Next <Icon name="arrowRight" size={14} /></Link>}</div></nav></div>;
}
