'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import type { Comment } from '@/lib/types';

export default function AdminCommentsPage() {
  const [comments, setComments] = useState<Comment[]>([]); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); const { data } = await createClient().from('comments').select('*').order('created_at', { ascending: false }); setComments((data ?? []) as Comment[]); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function setStatus(id: string, status: Comment['status']) { const { error } = await createClient().from('comments').update({ status }).eq('id', id); if (!error) setComments((rows) => rows.map((row) => row.id === id ? { ...row, status } : row)); }
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Moderation</p><h1 className="mt-1 text-3xl font-extrabold text-navy">Comments</h1><p className="mt-2 text-sm text-ink/55">Review community notes. Database RLS permits this view and moderation only for admins.</p></header>{loading ? <p className="text-sm text-ink/50">Loading comments…</p> : comments.length === 0 ? <div className="card p-8 text-center text-sm text-ink/50">No comments yet.</div> : <div className="space-y-3">{comments.map((comment) => <article key={comment.id} className="card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="rounded-md bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{comment.item_type}</span><span className="text-xs text-ink/45">{new Date(comment.created_at).toLocaleString()}</span></div><span className={`rounded-md px-2 py-1 text-xs font-bold ${comment.status === 'visible' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{comment.status}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-ink/80">{comment.content}</p><div className="mt-4 flex gap-2">{comment.status !== 'visible' && <button onClick={() => setStatus(comment.id, 'visible')} className="btn-secondary px-3 py-1.5 text-xs">Restore</button>}{comment.status !== 'hidden' && <button onClick={() => setStatus(comment.id, 'hidden')} className="btn-secondary px-3 py-1.5 text-xs">Hide</button>}{comment.status !== 'deleted' && <button onClick={() => setStatus(comment.id, 'deleted')} className="btn-danger px-3 py-1.5 text-xs">Delete</button>}</div></article>)}</div>}</div>;
}
